"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, RotateCcw, Skull, TriangleAlert } from "lucide-react";
import { easeOut } from "@/lib/media";
import { Action, Eyebrow, Pill } from "@/components/ui/Kit";
import { useQuarter } from "@/components/quarter/QuarterProvider";
import {
  BalanceSheetPanel,
  GatePanel,
  ModifierList,
  TraitCard,
} from "@/components/quarter/ReportBits";
import { formatRupees } from "@/lib/quarter/types";

/* Screen 10 — Quarter Report. Two halves matching the backend's two
   parallel outputs: Business Impact (KPI scorecard + balance sheet +
   gate callouts) and the CEO Score (7 traits + modifier layer). */

export default function ReportPage() {
  const { quarter, result, reset } = useQuarter();

  if (!result) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-16 text-center sm:px-8">
        <p className="text-[15px] text-dim">
          This quarter has not run yet — the report is generated by
          run_quarter().
        </p>
        <div className="mt-6 inline-flex">
          <Action href={`/quarter/${quarter}/approval`}>
            Go to Quarter Approval <ArrowRight className="h-4 w-4" />
          </Action>
        </div>
      </div>
    );
  }

  const impact = result.business_impact;
  const failed = result.run_status === "FAILED";
  const distressed = result.run_status === "DISTRESSED";
  const traitTotal = result.scoring.traits.reduce((a, t) => a + t.points_earned, 0);
  const modifierNet = result.scoring.modifiers.reduce((a, m) => a + m.points, 0);

  const ledger: [string, number, boolean?][] = [
    ["Revenue", impact.revenue],
    ["COGS", -impact.cogs],
    ["Gross profit", impact.gross_profit, true],
    ["Warranty cost", impact.warranty_cost],
    ["Inventory holding cost", impact.inventory_holding_cost],
    ["Fixed costs", impact.fixed_costs],
    ["Discretionary spend", impact.discretionary_spend],
    ["Net cash flow", impact.net_cash_flow, true],
  ];

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-8 sm:py-10">
      {/* header — post-mortem treatment when the company failed */}
      <motion.header
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: easeOut }}
      >
        <div className="flex flex-wrap items-center gap-3">
          <Eyebrow accent={failed ? "rose" : "violet"}>
            Quarter {quarter} · Report
          </Eyebrow>
          <Pill accent={failed ? "rose" : distressed ? "amber" : "emerald"}>
            {result.run_status}
          </Pill>
          <span className="num text-[11px] text-faint">{result.result_hash}</span>
        </div>
        <h1 className="display mt-4 text-[clamp(1.7rem,3.5vw,2.6rem)] text-ink">
          {failed
            ? "The company didn't survive the quarter."
            : distressed
              ? "You survived — barely."
              : "The quarter is in the books."}
        </h1>
      </motion.header>

      {failed && (
        <div className="mt-5 flex items-start gap-3 rounded-xl border border-rose/35 bg-rose/[0.07] p-4">
          <Skull className="mt-0.5 h-4 w-4 shrink-0 text-rose" />
          <p className="text-[13.5px] leading-relaxed text-dim">
            Cash went negative before quarter end. What follows reads as a
            post-mortem: the numbers, the gates that bound you, and the
            judgment record — because the record is what you keep.
          </p>
        </div>
      )}
      {distressed && !failed && (
        <div className="mt-5 flex items-start gap-3 rounded-xl border border-amber/30 bg-amber/[0.07] p-4">
          <TriangleAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber" />
          <p className="text-[13.5px] leading-relaxed text-dim">
            The company is in a distressed state — cash cleared the floor but
            not by much. Next quarter starts with less room for error.
          </p>
        </div>
      )}

      <div className="mt-8 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]">
        {/* half A — business impact */}
        <div className="space-y-4">
          <h2 className="eyebrow text-faint">A · Business impact</h2>

          <div className="overflow-hidden rounded-xl border border-line bg-raise/50">
            <div className="flex items-center justify-between border-b border-white/[0.05] px-4 py-3">
              <span className="text-[13px] text-dim">Units sold</span>
              <span className="num text-[15px] font-semibold text-ink">
                {impact.units_sold.toLocaleString("en-IN")}
              </span>
            </div>
            <div className="divide-y divide-white/[0.04]">
              {ledger.map(([label, amount, bold]) => (
                <div
                  key={label}
                  className="flex items-center justify-between px-4 py-2.5"
                >
                  <span
                    className={`text-[12.5px] ${bold ? "font-medium text-ink" : "text-dim"}`}
                  >
                    {label}
                  </span>
                  <span
                    className={`num text-[13px] ${bold ? "font-semibold" : ""}`}
                    style={{
                      color:
                        amount < 0 ? "var(--rose)" : bold ? "var(--emerald)" : "var(--ink)",
                    }}
                  >
                    {formatRupees(amount)}
                  </span>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between border-t border-white/[0.08] bg-white/[0.02] px-4 py-3">
              <span className="text-[13px] font-medium text-ink">
                Cash balance · end of quarter
              </span>
              <span
                className="num text-[15px] font-semibold"
                style={{ color: impact.cash_balance < 0 ? "var(--rose)" : "var(--ink)" }}
              >
                {formatRupees(impact.cash_balance)}
              </span>
            </div>
          </div>

          <BalanceSheetPanel sheet={impact.balance_sheet} />

          <div>
            <h3 className="mb-3 text-[14px] font-medium text-ink">
              What limited your results this quarter
            </h3>
            <GatePanel gates={result.gates_triggered} />
          </div>
        </div>

        {/* half B — CEO score */}
        <div className="space-y-4">
          <h2 className="eyebrow text-faint">B · CEO score</h2>

          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5, delay: 0.15, ease: easeOut }}
            className="ring-grad relative overflow-hidden rounded-2xl p-[1px]"
          >
            <div className="rounded-2xl bg-raise px-5 py-6 text-center">
              <p className="display text-[54px] leading-none text-grad">
                {result.scoring.final_score}
                <span className="text-[22px] text-faint">/100</span>
              </p>
              <p className="eyebrow mt-3 text-ink">
                {result.scoring.band} CEO
              </p>
            </div>
          </motion.div>

          <div className="space-y-2">
            {result.scoring.traits.map((trait, i) => (
              <TraitCard key={trait.name} trait={trait} delay={0.1 + i * 0.05} />
            ))}
          </div>

          <ModifierList modifiers={result.scoring.modifiers} />

          <p className="num rounded-lg border border-line bg-white/[0.02] px-4 py-3 text-center text-[11.5px] text-faint">
            Final Score = Σ(Trait Points) + Σ(Modifiers) = {traitTotal}{" "}
            {modifierNet >= 0 ? `+ ${modifierNet}` : `− ${Math.abs(modifierNet)}`} ={" "}
            {result.scoring.final_score}
          </p>
        </div>
      </div>

      {/* onward */}
      <footer className="mt-10 flex flex-wrap items-center justify-between gap-4 border-t border-line pt-6">
        <button
          type="button"
          onClick={reset}
          className="flex items-center gap-2 text-[13px] text-dim transition-colors hover:text-ink"
        >
          <RotateCcw className="h-3.5 w-3.5" />
          Re-run this quarter with fresh decisions
        </button>
        <div className="flex flex-wrap items-center gap-3">
          <Link
            href="/leaderboard"
            className="text-[13px] text-dim transition-colors hover:text-ink"
          >
            Leaderboard
          </Link>
          {quarter >= 3 && (
            <Action href={`/quarter/${quarter}/endgame`} variant="outline">
              Term sheets
            </Action>
          )}
          {!failed && (
            <Action href={`/quarter/${quarter + 1}/briefing`}>
              Start Q{quarter + 1}
              <ArrowRight className="h-4 w-4" />
            </Action>
          )}
        </div>
      </footer>
    </div>
  );
}
